### PR TITLE
Travis: Add gcc 4.4 and 4.5

### PR DESCRIPTION
**Pull request by scop**

### CODE REVIEW

**Comment by nelhage** [comment]
I'm not opposed to this, but I'm curious if there was a specific motivation here. Did you run into problems with a particular GCC version or do you think reptyr is particularly likely to run into such problems?

**Comment by scop** [comment]
It's something I tried while trying to track down #67, #68, and #69.

-Werror in reptyr's CFLAGS does make it prone to build errors with different compiler versions (and other stuff in CFLAGS, like demonstrated by #68). Maybe the Travis builds should in addition to different compilers be build both without any -O (like at the moment) as well as with e.g. -O2?

**Comment by nelhage** [comment]
My suspicion is that 4.4 and 4.5 aren't disparate enough to be likely to surface bugs, and that a lot of your problems are related to older kernel headers, which unfortunately aren't easy to test via Travis.

I'd be happy to take a change to optionally disable `-Werror` in the `Makefile`, if that would make your life easier in that regard.

**Comment by scop** [comment]
Well, there's not much difference in say ```make WERROR=``` and ```sed -i -e 's/ -Werror//' Makefile```, especially since I'm dealing with the Fedora/EPEL reptyr package builds which means I won't be typing that often at all. But it would be cleaner if the ```CFLAGS``` I set anyway would be appended to the reptyr defaults instead of the other way around; then I could do ```make CFLAGS="$whatever_i_do_anyway -Wno-error"```, maybe something like:

```diff
--- a/Makefile
+++ b/Makefile
@@ -1,4 +1,5 @@
-override CFLAGS+=-Wall -Werror -D_GNU_SOURCE -g
+ALL_CFLAGS := -Wall -Werror -D_GNU_SOURCE -g $(CFLAGS)
+override CFLAGS = $(ALL_CFLAGS)
```

**Comment by nelhage** [comment]
How do you feel about that fix I just pushed?

**Comment by scop** [comment]
Seems fine, thanks.

**Pull request closed without merging**
